CODEFLOW_WORDS: tuple[tuple[str, str], ...] = (
    ("sketch", "the rough drawing that explains it faster than prose"),
    ("flow", "the path control actually takes"),
    ("diagram", "the picture of the system"),
    ("trace", "following one call the whole way down"),
    ("graph", "nodes and the edges between them"),
    ("map", "the whole territory on one page"),
    ("chart", "the drawing you navigate by"),
    ("path", "the route through"),
    ("route", "how a request finds its handler"),
    ("link", "the connection between two things"),
    ("node", "one box in the picture"),
    ("edge", "the line between two boxes"),
    ("branch", "where the decision splits"),
    ("merge", "where the branches come back together"),
    ("fork", "the point of divergence"),
    ("stack", "the frames, top to bottom"),
    ("trail", "the markers left for whoever follows"),
    ("thread", "one continuous line of execution"),
    ("scope", "what is visible from here"),
    ("grid", "the frame everything aligns to"),
    ("mesh", "the connective net"),
    ("schema", "the shape the data has to take"),
    ("atlas", "the bound collection of maps"),
    ("legend", "the key that makes the symbols readable"),
    ("compass", "which way is north"),
    ("beacon", "the thing you can see from far off"),
    ("signal", "what carries meaning through the noise"),
    ("cipher", "the code, and the key to it"),
    ("glyph", "a single symbol that stands for something"),
    ("symbol", "the name the compiler resolves"),
    ("draft", "the version before the version"),
    ("outline", "the shape before the detail"),
    ("layout", "where everything sits"),
    ("canvas", "the surface it gets drawn on"),
    ("vector", "direction and magnitude in one"),
    ("circuit", "the closed loop that carries current"),
    ("lens", "what brings it into focus"),
    ("insight", "the thing you see once it is drawn"),
    ("ledger", "the record of what happened"),
    ("index", "how you find the one thing you need"),
    ("primer", "the first thing a newcomer reads"),
    ("guide", "the person who has walked it before"),
    ("tour", "the walk through the codebase"),
    ("relay", "passing it on without dropping it"),
    ("bridge", "what joins two sides"),
    ("anchor", "the fixed point everything references"),
    ("pointer", "the thing that says look over there"),
    ("pivot", "the point the whole thing turns on"),
    ("cursor", "where you are right now"),
    ("parse", "reading structure out of text"),
)
