GRAPHEMES: dict[str, tuple[str, ...]] = {
    "SK": ("sk", "sc", "sq", "sch", "skh"),
    "SP": ("sp", "spp", "sph"),
    "TR": ("tr", "trr", "thr"),
    "GR": ("gr", "grr", "ghr"),
    "GL": ("gl", "gll", "ghl"),
    "THR": ("thr", "thhr", "phr"),
    "CH": ("ch", "tch", "tsch", "tj", "cz"),
    "SH": ("sh", "sch", "ch", "ti"),
    "K": ("k", "c", "ck", "q", "kh"),
    "S": ("s", "c", "ss", "z", "ce"),
    "T": ("t", "tt", "te", "th"),
    "D": ("d", "dd", "de"),
    "P": ("p", "pp", "pe"),
    "F": ("f", "ph", "ff", "gh"),
    "V": ("v", "vv", "ve"),
    "J": ("j", "ge", "dge", "g"),
    "M": ("m", "mm", "me"),
    "R": ("r", "rr", "rh"),
    "EH": ("e", "y", "ea", "ai", "ae", "eh", "a"),
    "IH": ("i", "y", "ie", "ee", "ea"),
    "AA": ("a", "aa", "ah", "ar"),
    "AY": ("ay", "a", "ai", "ei", "ey", "ae"),
    "OH": ("o", "oa", "oe", "ough", "ow"),
    "AR": ("ar", "a", "arr", "ahr"),
    "OR": ("or", "oar", "aur", "orr"),
    "ER": ("er", "ur", "ir", "yr", "ar"),
}

WORD_SOUNDS: dict[str, tuple[str, ...]] = {
    "sketch": ("SK", "EH", "CH"),
    "scope": ("SK", "OH", "P"),
    "trace": ("TR", "AY", "S"),
    "graph": ("GR", "AA", "F"),
    "glyph": ("GL", "IH", "F"),
    "chart": ("CH", "AR", "T"),
    "thread": ("THR", "EH", "D"),
    "spark": ("SP", "AR", "K"),
    "forge": ("F", "OR", "J"),
    "map": ("M", "AA", "P"),
    "mesh": ("M", "EH", "SH"),
    "grid": ("GR", "IH", "D"),
}

MAX_RESPELLING_LENGTH = 9
