SEED_NAMES: tuple[tuple[str, str], ...] = (
    ("Clew", "the ball of thread Ariadne gave Theseus, and the origin of the word 'clue'"),
    ("Sheaf", "the mathematics of gluing local views into one coherent global picture"),
    ("Cairn", "stacked stones left on the path to mark the way for whoever comes next"),
    ("Sightglass", "the transparent window in a pipe that lets you watch the flow without stopping it"),
    ("Throughline", "the connecting thread that runs through the whole story"),
    ("Lodestone", "the stone that always points north and pulls other things to it"),
    ("Keel", "the spine that keeps a ship upright and on an even keel"),
    ("Tessera", "the single tile that only makes sense as part of the mosaic"),
    ("Bearing", "getting your bearings, and the load-bearing parts of the structure"),
    ("Plumbline", "the simple tool that tells you the truth about what is straight"),
    ("Weft", "the thread woven across the warp that turns loose strands into cloth"),
    ("Braid", "separate strands that are stronger bound together than apart"),
    ("Ferrule", "the collar that binds the handle to the blade"),
    ("Tenon", "the joint that locks two pieces into one without glue"),
    ("Girder", "the beam the whole structure hangs off"),
    ("Bindery", "where loose pages become a book"),
    ("Aquifer", "the shared reservoir under everything that everyone draws from"),
    ("Groundplan", "the honest layout of the building, drawn before anything is built"),
    ("Wayfinder", "designing a space so a stranger can navigate it without asking"),
    ("Sightline", "an unobstructed line from where you stand to what you need to see"),
    ("Limpid", "so clear you can see straight through it"),
    ("Vitrine", "the glass case where nothing is hidden"),
    ("Glasswing", "the butterfly you can see through"),
    ("Candor", "openness, said plainly"),
    ("Verity", "the plain truth of the thing"),
    ("Clarion", "a clear call that everybody hears"),
    ("Meridian", "the line you orient everything else against"),
    ("Sinew", "connective tissue: what makes the whole body pull in one direction"),
    ("Marrow", "the living core inside the structure"),
    ("Kiln", "where something soft is fired into something durable"),
    ("Hearth", "where the team gathers and knowledge gets handed down"),
    ("Contour", "the lines that reveal the shape of the ground"),
    ("Trellis", "the frame that supports growth and shows its shape"),
    ("Keystone", "the stone that holds the arch up"),
    ("Anneal", "the heat that leaves the material stronger and less brittle"),
    ("Skein", "one continuous thread, coiled so it can be followed"),
    ("Dowel", "the hidden peg that holds two pieces together"),
    ("Gantry", "the frame that carries the load and sets it in place"),
    ("Osmosis", "the way knowledge used to spread, until the person left"),
    ("Breadcrumb", "the trail left for whoever follows"),
    ("Lodestar", "the star you steer by"),
    ("Fathom", "to understand deeply, and to measure the depth"),
    ("Commons", "knowledge held by everyone instead of enclosed by anyone"),
    ("Ariadne", "the thread that leads out of the labyrinth"),
    ("Rosetta", "the stone that made an unreadable language readable"),
    ("Legend", "the key on a map that makes every symbol readable, and the lore itself"),
    ("Diaphane", "diaphanous: the material that lets the light through"),
    ("Pellucid", "clear the whole way through"),
    ("Clewline", "the thread line traced through the maze"),
    ("Cairnworks", "the workshop that builds the markers"),
    ("Sheafworks", "the workshop that glues the local views together"),
    ("Keelworks", "the workshop that lays the spine"),
    ("Plainsight", "everything in plain sight, nothing hidden behind anyone's head"),
    ("Clewstone", "the guiding thread, set in something permanent"),
    ("Keelstone", "the spine of the ship and the stone of the arch in one word"),
    ("Sheafline", "the line that gathers the loose stalks into one bundle"),
    ("Cairnlight", "a marker on the path you can see from a long way off"),
    ("Weftline", "the cross-thread that binds the warp into cloth"),
    ("Trueweave", "woven straight and true"),
    ("Bindloom", "the loom that binds separate strands into one fabric"),
    ("Knotwise", "knowing where the knots are before you hit them"),
    ("Veritrace", "tracing the truth through the system"),
    ("Openweave", "a weave open enough to see through"),
    ("Northweft", "the binding thread that also points north"),
    ("Glasskeel", "a spine you can see through"),
    ("Truthframe", "the frame that holds the honest picture"),
    ("Wayline", "the line that shows the way through"),
    ("Loomstone", "where the threads are held while they are woven"),
    ("Threadstone", "the thread made permanent"),
    ("Cairnpath", "the path with the markers already on it"),
    ("Sightweave", "clear view and connective tissue in one"),
    ("Clearweft", "the binding thread, in the open"),
)
