OPTICAL_SEED_NAMES: tuple[tuple[str, str], ...] = (
    ("Holobase", "a hologram of the codebase: the whole thing, from any angle"),
    ("Holomap", "the map you can walk around"),
    ("Holoscope", "the instrument you look through to see the whole"),
    ("Holograph", "written wholly in one hand, and a hologram in the same word"),
    ("Holoweave", "the whole picture, woven from every strand"),
    ("Holoframe", "the frame that holds the whole projection"),
    ("Holostack", "every layer of the system, projected at once"),
    ("Glyphbase", "the symbols that carry the meaning"),
    ("Glyphscope", "the instrument that resolves the symbols"),
    ("Glyphweave", "symbols woven into one readable surface"),
    ("Scryline", "to scry: to see clearly what is happening somewhere else"),
    ("Scrybase", "the surface you look into to see the system"),
    ("Scrymap", "the far-seeing map"),
    ("Prismap", "one beam split so you can see every colour inside it"),
    ("Prismbase", "the surface that separates the light"),
    ("Lumenbase", "the unit of light, applied to the codebase"),
    ("Lumascope", "an instrument for measuring how much light gets through"),
    ("Lumagraph", "drawn in light"),
    ("Stratamap", "the layers of the system, drawn in cross-section"),
    ("Stratabase", "the strata under everything the team builds"),
    ("Stratascope", "the instrument that reads the layers"),
    ("Axonmesh", "axons: the wiring that carries signal between the parts"),
    ("Axonbase", "the network that carries what everyone knows"),
    ("Axongraph", "the signal paths, drawn"),
    ("Cipherscope", "the instrument that makes the cipher readable"),
    ("Cipherbase", "where the decoding lives"),
    ("Hyaloscope", "hyaline: clear as glass, all the way through"),
    ("Hyalobase", "the glass-clear substrate"),
    ("Vitriscope", "vitreous: seen through glass"),
    ("Panoscope", "the whole panorama in one instrument"),
    ("Panograph", "the wide view, drawn"),
    ("Parallax", "two viewpoints combined into real depth"),
    ("Parallaxcore", "depth at the centre of it"),
    ("Refract", "bending light so the structure inside becomes visible"),
    ("Refractbase", "where the light bends and the shape appears"),
    ("Codeglass", "glass laid over the code: nothing hidden underneath"),
    ("Glassgraph", "the diagram you can see straight through"),
    ("Glassbase", "a transparent foundation"),
    ("Clearstack", "every layer, in the clear"),
    ("Clearmesh", "the connective net, out in the open"),
    ("Lightgraph", "the graph drawn in light"),
    ("Lucidstack", "lucid: clear, and immediately understood"),
    ("Translucid", "translucent and lucid at once"),
    ("Causticmap", "the caustic: the bright pattern light makes when it passes through"),
    ("Albedobase", "albedo: how much light a surface gives back"),
    ("Facetmap", "every facet of the thing, at once"),
    ("Aperturebase", "the opening that lets the light in"),
    ("Lumenweave", "light and connective tissue in one"),
)
