KIND_DOMAIN = "domain"
KIND_PRIOR_ART = "prior_art"

DOMAIN_TAKEN = "taken"
DOMAIN_AVAILABLE = "available"
DOMAIN_LIKELY_AVAILABLE = "likely_available"
DOMAIN_UNKNOWN = "unknown"

PRIOR_ART_HIT = "hit"
PRIOR_ART_CLEAR = "clear"
PRIOR_ART_UNKNOWN = "unknown"

VERDICT_STRONG = "strong"
VERDICT_CHECK = "check"
VERDICT_REJECT = "reject"
VERDICT_UNKNOWN = "unknown"

DOMAIN_FREE_STATUSES = (DOMAIN_AVAILABLE, DOMAIN_LIKELY_AVAILABLE)
VERDICT_ORDER = (VERDICT_STRONG, VERDICT_CHECK, VERDICT_UNKNOWN, VERDICT_REJECT)
