from typing import Protocol


class AccessTokenStore(Protocol):
    async def create(
        self, user_id: int, kind: str, name: str | None, token_hash: str, prefix: str
    ) -> int: ...

    async def get_by_hash(self, token_hash: str) -> dict | None: ...

    async def list_for_user(self, user_id: int, kind: str) -> list[dict]: ...

    async def revoke(self, user_id: int, token_id: int) -> bool: ...

    async def touch_last_used(self, token_id: int) -> None: ...
